import { Router, type IRouter } from "express";
import healthRouter from "./health";
import workflowsRouter from "./workflows";
import assetsRouter from "./assets";
import alertsRouter from "./alerts";
import dashboardRouter from "./dashboard";
import analyticsRouter from "./analytics";
import itemsRouter from "./items";
import documentsRouter from "./documents";
import propertiesRouter from "./properties";
import assignmentsRouter from "./assignments";
import drillRouter from "./drill";
import workOrdersRouter from "./work-orders";
import turnsRouter from "./turns";
import reportsRouter from "./reports";
import governanceRouter from "./governance";
import reportingIngestionRouter from "./reporting-ingestion";
import reportingAnalysisRouter from "./reporting-analysis";
import reportingConfigRouter from "./reporting-config";
import narrativeInsightsRouter from "./narrative-insights";
import buildAuditorRouter from "./build-auditor";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(workflowsRouter);
router.use("/workflows/:id/items", itemsRouter);
router.use(assetsRouter);
router.use(alertsRouter);
router.use(analyticsRouter);
router.use(documentsRouter);
router.use(propertiesRouter);
router.use(assignmentsRouter);
router.use(drillRouter);
router.use(workOrdersRouter);
router.use(turnsRouter);
router.use(reportsRouter);
router.use(governanceRouter);
router.use(reportingIngestionRouter);
router.use(reportingAnalysisRouter);
router.use(reportingConfigRouter);
router.use(narrativeInsightsRouter);
router.use(buildAuditorRouter);

export default router;
